// <auto-generated />
namespace USoftEducation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class optionalentityitems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(optionalentityitems));
        
        string IMigrationMetadata.Id
        {
            get { return "201806140404529_optional entity items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
